"""Initial migration

Revision ID: 7b94eabfab58
Revises: 
Create Date: 2023-08-09 21:37:29.592209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b94eabfab58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_degree', sa.String(), nullable=True),
    sa.Column('group_point', sa.String(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=150), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_first_name', sa.String(), nullable=False),
    sa.Column('teacher_last_name', sa.String(), nullable=False),
    sa.Column('teacher_incumbency', sa.String(), nullable=False),
    sa.Column('teacher_degree', sa.String(), nullable=True),
    sa.Column('teacher_age', sa.Integer(), nullable=True),
    sa.Column('teacher_email', sa.String(length=100), nullable=True),
    sa.Column('teacher_phone_number', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(), nullable=False),
    sa.Column('student_last_name', sa.String(), nullable=False),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.Column('student_birthday', sa.Date(), nullable=True),
    sa.Column('student_email', sa.String(length=100), nullable=True),
    sa.Column('student_phone_number', sa.String(), nullable=True),
    sa.Column('student_course', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ects_points', sa.Integer(), nullable=True),
    sa.Column('grade_ects', sa.String(length=2), nullable=True),
    sa.Column('old_system_grade', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('groups')
    # ### end Alembic commands ###
