"""Initial migration contacts

Revision ID: 0cfa5e8a9eb8
Revises: e80193ad7c3c
Create Date: 2023-09-10 15:14:15.975538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfa5e8a9eb8'
down_revision: Union[str, None] = 'e80193ad7c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
