version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - myapp-network

  postgres:
    image: postgres:12
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - myapp-network
  myapp:
    build:
      context: .
    container_name: myapp-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - /home/kagev/PycharmProjects/MyCode/GoIT_Homework/WEB/HW13:/path/inside/container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    networks:
      - myapp-network

networks:
  myapp-network:

